version: '2'

services:
  openresty:
    build: ./openresty
    volumes:
      - ./openresty/conf/nginx.conf:/etc/nginx/conf.d/conf/nginx.conf
      - ./openresty/conf/upstream.conf:/usr/local/openresty/nginx/conf/upstream.conf
      - ./openresty/sites:/usr/local/openresty/nginx/conf/sites
      - ${APPLICATION_PATH}:/var/www/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
      - backend
      
  apache:
    build: ./apache
    volumes:
      - ${APPLICATION_PATH}:/var/www/
      - ./apache/sites:/etc/apache2/sites-available
    ports:
      - "8080:80"
    networks:
      - frontend
      - backend

  php-fpm:
    build:
      context: ./php-fpm
      # args:
      #   - PHP_OPCACHE=${PHP_OPCACHE}
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      # - ./php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ${APPLICATION_PATH}:/var/www
    networks:
      - backend

  phpmyadmin:
    build: ./phpmyadmin
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=
    ports:
      - "8888:80"
    networks:
      - frontend
      - backend

  mysql:
    build: ./mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    networks:
      - backend

  redis:
    build: ./redis
    volumes:
      - ./data/redis:/data
    networks:
      - backend

  portainer:
    build: ./portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    ports:
      - "9000:9000"
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend: