version: '2'

services:
  openresty:
    build: ./openresty
    volumes:
      - ./openresty/conf/nginx.conf:/etc/nginx/conf.d/conf/nginx.conf
      - ./openresty/conf/upstream.conf:/usr/local/openresty/nginx/conf/upstream.conf
      - ./openresty/sites:/usr/local/openresty/nginx/conf/sites
      - ${APPLICATION_PATH}:/var/www/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
      - backend
      
  php-fpm:
    build:
      context: ./php-fpm
      # args:
      #   - PHP_OPCACHE=${PHP_OPCACHE}
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      # - ./php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ${APPLICATION_PATH}:/var/www
    networks:
      - backend

  mysql:
    build: ./mysql
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    networks:
      - backend

  redis:
    build: ./redis
    volumes:
      - ${DATA_PATH}/redis:/data
    networks:
      - backend

networks:
  frontend:
  backend: