version: "3"
services:

  workspace:
    container_name: workspace
    build:
      context: ./workspace
      args:
        - CHINA_MIRROR=${CHINA_MIRROR}
        - DEFAULT_TIMEZONE=${DEFAULT_TIMEZONE}
        - PHP_EXT_OPCACHE=${WORKSPACE_ENABLE_OPCACHE}
        - PHP_EXT_XDEBUG=${WORKSPACE_ENABLE_XDEBUG}
        - PHP_EXT_IMAGICK=${PHP_EXT_IMAGICK}
        - PHP_EXT_GD=${PHP_EXT_GD}
        - PHP_EXT_REDIS=${PHP_EXT_REDIS}
        - PHP_EXT_MCRYPT=${PHP_EXT_MCRYPT}
    tty: true
    volumes:
      - ${APP_PATH}:/var/www
      - ${DATA_PATH}:/var/data
      - ${LOGS_PATH}:/var/logs
      - ./workspace/php.ini:/usr/local/etc/php/php.ini
      - ./workspace/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./workspace/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - backend

  lsyncd:
    container_name: lsyncd
    build:
      context: ./lsyncd
      args:
        - CHINA_MIRROR=${CHINA_MIRROR}
        - DEFAULT_TIMEZONE=${DEFAULT_TIMEZONE}
    volumes:
      - ${APP_PATH}:/var/www
      - ${DATA_PATH}:/var/data
      - ${LOGS_PATH}:/var/logs
      - ./lsyncd/lsyncd.conf:/etc/lsyncd/lsyncd.conf
      - ./lsyncd/rsync.conf:/etc/rsync/rsync.conf
      - ./lsyncd/rsync.secrets:/etc/rsync/rsync.secrets
      - ./lsyncd/rsync.password:/etc/rsync/rsync.password
    ports:
      - "873:873"
    networks:
      - backend

  cron:
    container_name: cron
    build:
      context: ./cron
      args:
        - CHINA_MIRROR=${CHINA_MIRROR}
        - DEFAULT_TIMEZONE=${DEFAULT_TIMEZONE}
        - PHP_EXT_OPCACHE=${CRON_ENABLE_OPCACHE}
        - PHP_EXT_XDEBUG=${CRON_ENABLE_XDEBUG}
        - PHP_EXT_IMAGICK=${PHP_EXT_IMAGICK}
        - PHP_EXT_GD=${PHP_EXT_GD}
        - PHP_EXT_REDIS=${PHP_EXT_REDIS}
        - PHP_EXT_MCRYPT=${PHP_EXT_MCRYPT}
    volumes:
      - ${APP_PATH}:/var/www
      - ${LOGS_PATH}:/var/logs
      - ./cron/shell:/var/shell
      - ./cron/conf/cronjobs:/etc/crontabs/root
      - ./cron/php.ini:/usr/local/etc/php/php.ini
      - ./cron/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./cron/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - backend

  haproxy:
    container_name: haproxy
    build: 
      context: ./haproxy
      args:
        - CHINA_MIRROR=${CHINA_MIRROR}
        - DEFAULT_TIMEZONE=${DEFAULT_TIMEZONE}
    volumes:
      - ${LOGS_PATH}:/var/logs
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
      - backend

  openresty:
    container_name: openresty
    build: 
      context: ./openresty
      args:
        - CHINA_MIRROR=${CHINA_MIRROR}
        - DEFAULT_TIMEZONE=${DEFAULT_TIMEZONE}
    volumes:
      - ./openresty/conf/nginx.conf:/etc/nginx/conf.d/conf/nginx.conf
      - ./openresty/conf/upstream.conf:/usr/local/openresty/nginx/conf/upstream.conf
      - ./openresty/conf/snippets:/usr/local/openresty/nginx/conf/snippets
      - ./openresty/sites:/usr/local/openresty/nginx/conf/sites
      - ${APP_PATH}:/var/www
      - ${LOGS_PATH}:/var/logs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
      - backend
      
  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
      args:
        - CHINA_MIRROR=${CHINA_MIRROR}
        - DEFAULT_TIMEZONE=${DEFAULT_TIMEZONE}
        - PHP_EXT_OPCACHE=${PHP_FPM_ENABLE_OPCACHE}
        - PHP_EXT_XDEBUG=${PHP_FPM_ENABLE_XDEBUG}
        - PHP_EXT_IMAGICK=${PHP_EXT_IMAGICK}
        - PHP_EXT_GD=${PHP_EXT_GD}
        - PHP_EXT_REDIS=${PHP_EXT_REDIS}
        - PHP_EXT_MCRYPT=${PHP_EXT_MCRYPT}
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ${APP_PATH}:/var/www
      - ${LOGS_PATH}:/var/logs
    networks:
      - backend

  phpmyadmin:
    container_name: phpmyadmin
    build: 
      context: ./phpmyadmin
      args:
        - CHINA_MIRROR=${CHINA_MIRROR}
        - DEFAULT_TIMEZONE=${DEFAULT_TIMEZONE}
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./phpmyadmin/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "8888:80"
    networks:
      - frontend
      - backend

  mysql:
    container_name: mysql
    build: 
      context: ./mysql
      args:
        - CHINA_MIRROR=${CHINA_MIRROR}
        - DEFAULT_TIMEZONE=${DEFAULT_TIMEZONE}
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ${LOGS_PATH}:/var/logs
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # - MYSQL_ALLOW_EMPTY_PASSWORD=true
    # ports:
    #  - "3306:3306"
    networks:
      - backend

  redis:
    container_name: redis
    build: 
      context: ./redis
      args:
        - CHINA_MIRROR=${CHINA_MIRROR}
        - DEFAULT_TIMEZONE=${DEFAULT_TIMEZONE}
    volumes:
      - ${DATA_PATH}/redis:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    # ports:
    #  - "6379:6379"
    networks:
      - backend

  rabbitmq:
    container_name: rabbitmq
    build: 
      context: ./rabbitmq
      args: 
        - CHINA_MIRROR=${CHINA_MIRROR}
        - DEFAULT_TIMEZONE=${DEFAULT_TIMEZONE}
    volumes:
      - ${DATA_PATH}/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=vhost
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    # ports:
      # - "5672:5672"
      # - "15672:15672"
    networks:
      - frontend
      - backend


  portainer:
    container_name: portainer
    build: 
      context: ./portainer
      args:
        - CHINA_MIRROR=${CHINA_MIRROR}
        - DEFAULT_TIMEZONE=${DEFAULT_TIMEZONE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_PATH}/portainer:/data
    ports:
      - "9000:9000"
    networks:
      - frontend

  gogs:
    container_name: gogs
    build: 
      context: ./gogs
      args:
        - CHINA_MIRROR=${CHINA_MIRROR}
        - DEFAULT_TIMEZONE=${DEFAULT_TIMEZONE}
    volumes:
      - ${DATA_PATH}/gogs:/data
    ports:
      # - "10022:22"
      - "10080:3000"
    networks:
      - frontend
      - backend


networks:
  frontend:
  backend: