version: "3"
services:

  workspace:
    container_name: workspace
    build: ./workspace
    tty: true
    volumes:
      - ${APP_PATH}:/var/www
      - ${DATA_PATH}:/var/data
      - ${LOGS_PATH}:/var/logs
      - ./workspace/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    networks:
      - backend

  lsyncd:
    container_name: lsyncd
    build: ./lsyncd
    volumes:
      - ${APP_PATH}:/var/www
      - ${DATA_PATH}:/var/data
      - ${LOGS_PATH}:/var/logs
      - ./lsyncd/lsyncd.conf:/etc/lsyncd/lsyncd.conf
      - ./lsyncd/rsync.conf:/etc/rsync/rsync.conf
      - ./lsyncd/rsync.secrets:/etc/rsync/rsync.secrets
      - ./lsyncd/rsync.password:/etc/rsync/rsync.password
    ports:
      - "873:873"
    networks:
      - backend

  cron:
    container_name: cron
    build: ./cron
    volumes:
      - ${APP_PATH}:/var/www
      - ${LOGS_PATH}:/var/logs
      - ./cron/shell:/var/shell
      - ./cron/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./cron/conf/cronjobs:/etc/crontabs/root
    networks:
      - backend

  haproxy:
    container_name: haproxy
    build: ./haproxy
    volumes:
      - ${LOGS_PATH}:/var/logs
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "80:8008"
      - "443:8009"
    networks:
      - frontend
      - backend

  openresty:
    container_name: openresty
    build: ./openresty
    volumes:
      - ./openresty/conf/nginx.conf:/etc/nginx/conf.d/conf/nginx.conf
      - ./openresty/conf/upstream.conf:/usr/local/openresty/nginx/conf/upstream.conf
      - ./openresty/conf/snippets:/usr/local/openresty/nginx/conf/snippets
      - ./openresty/sites:/usr/local/openresty/nginx/conf/sites
      - ${APP_PATH}:/var/www
      - ${LOGS_PATH}:/var/logs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
      - backend
      
  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./workspace/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ${APP_PATH}:/var/www
      - ${LOGS_PATH}:/var/logs
    networks:
      - backend

  phpmyadmin:
    container_name: phpmyadmin
    build: ./phpmyadmin
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8888:80"
    networks:
      - frontend
      - backend

  mysql:
    container_name: mysql
    build: ./mysql
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    # ports:
    #  - "3306:3306"
    networks:
      - backend

  redis:
    container_name: redis
    build: ./redis
    volumes:
      - ${DATA_PATH}/redis:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    # ports:
    #  - "6379:6379"
    networks:
      - backend

  rabbitmq:
    container_name: rabbitmq
    build: ./rabbitmq
    volumes:
      - ${DATA_PATH}/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=vhost
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    # ports:
      # - "5672:5672"
      # - "15672:15672"
    networks:
      - frontend
      - backend


  portainer:
    container_name: portainer
    build: ./portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_PATH}/portainer:/data
    ports:
      - "9000:9000"
    networks:
      - frontend

  gogs:
    container_name: gogs
    build: ./gogs
    volumes:
      - ${DATA_PATH}/gogs:/data
    ports:
      # - "10022:22"
      - "10080:3000"
    networks:
      - frontend
      - backend


networks:
  frontend:
  backend: